### ISSUE TITLE
About a fork of this project

### ISSUE THREAD

**Issue by Rix565** [JTechnologies/Polaris#31]
Hi!
I want to make me too an alternative platform of Scratch, can I fork this to have the base to make my own?

And don't worry the Polaris project will be in the credits ;)

**Comment by MikeDev101** [comment]
We're not ready yet for forking.

**Comment by Rix565** [comment]
Can we contact on Discord to discuss about that?

**Comment by VelocityDesign** [comment]
No. If you would like to fork, please do so strictly for contributing. This project *is* open source and free to fork, but the whole nature of Open-source is that you contribute back. If everyone just forks, it fragments the community and scatters our resources. So please, just stick with contributing to the project. (Also soon I will be creating a Polaris organization for anyone wondering)
